sudo: required

services:
  - docker
  
# when tests will work
#language: go
#go:
#- x.x.x #current go version

script:
  - export REPO=scalarm/scalarm_workers_manager
  - docker build . -f Dockerfile -t $REPO 
 

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS	
  - docker tag $REPO $REPO:$TRAVIS_TAG

deploy:
  - provider: script
    script:
      docker push $REPO 
    on:
      branch: master
      tags: true

env:
  global:
    - secure: "PaLqDGQ72uK1te04MHZwqjd2Fowx+0bTAJlxjuZRx08WcVsLWS+HEEA1IQ7vdAq6bthlFqvWunDe/Ufo4rWGNaZIBl4Pe8k5HJ69OvWSH6o4tqwgkd5dKTVkBk+gIREH7yJnmiaeqaATFlr6YkkBmPuI7NN/nx39kGoWc0glWTpe3mJF41lAumN20P4stuQEjzwE8yZHm40yBC//y5V3WjyB8Et5RGIRwrKgk9f73WiVzAVFReAWUGIdj0Wkg88/ERTH0+iS0XP+wjbk020EEDZMQahQMhZgtxQ0+XqZtM2SDEwma1C/8FFNGFhab+6bYRctkgWV+4aEGAvZuH27mpMMNpU5LPur7F92r3aoCSBDtTO5M1xo0JA3zIhmfKXmrP02B1LRseJjI/pelvdq9AHe9e/IQytLHU9lLOr4/EyHB6tMkf3aCljFyId+hSkFt0KwEdiKsXBSEdtBmVh5OyYINpPfvIC6ga/FPdaKSG9a2n5wQ6toIwMkgL9+hREZveF/ngoSz1aiUdYhchyuSbQYIajTZFnOygnZ4E1hIlR+EdCVr+pa+s365wFP6+0i11I90W8vIPIhts76GhNlcJm+5tCaO+PoJlpY3+isDjCyGBgzk/pZ6Pg1KIJc2HSdBtvbe9w0nhRSLVuGuiEoaYMEVBSLCpt9Gyu9RcSTv8w="
    - secure: "IDB+prW19NH4x4+t2Dvi6bAIWFCBvrl7OOUA4hCPe86RtveevOAEsXEgdHOIQJQiYBHunt86q4EcDg/pX2kPNKxDXFr7YTyUCRcvrLGkZU8IX2FCHymuNUjqFKDiLK3jbYCnJCfSZ1LFxSktsyjFsrYv3u0UQqCkZ7t+Qh+t+naD+2CJXsCJWtdTCRbjyGOpuZvsnU/lWf7jRrMEQy3qyYRGFLDtMX11QdQNnnikR1ukOEgW0MPO8cvP88TvkJDCprNIwuaGPzO0qijRGdfwouubeP36wSwmPntsrWnrkyeZ64i2bkdEPfPZE00cubKdmA53U/KP4nkNuaiyI68B2K96B317LglxR+siK9LNS7cgZlilymFXMt5fBeeUiekN754P/SCWxeWV+5vxgBtzYOgjOFUc6o1y+7fJ9vhoRrO3njw6s5alrI9QObq1qDszkoqUjnIox13iLQLvHfChzOgiNqQuGRa4ahgt3+qVyLe8pQoq6IR0MIoJGJzYvDFFZMWBwLzuy24KlIjemSIu0iNJLEd+fCJy6Zl8X5bp99rmAsGlr79mezBAGfywITj0ikABKJ/7LIDlKQZTAo5EdL41Q/pHPj8Q97eAa/xpcV8f6cFZRYVfh6oOwroVFOws+ZPkeJsHvZ3mrxa1iVGiFVo+gZdq3KyUZxl3Gwd3tTo="
 
  
